#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v3
# autospec commit: fae1327921d4
#
Name     : ngspice
Version  : 42
Release  : 9
URL      : https://sourceforge.net/projects/ngspice/files/ng-spice-rework/42/ngspice-42.tar.gz
Source0  : https://sourceforge.net/projects/ngspice/files/ng-spice-rework/42/ngspice-42.tar.gz
Summary  : General-purpose circuit simulator
Group    : Development/Tools
License  : GPL-3.0 MPL-2.0
Requires: ngspice-bin = %{version}-%{release}
Requires: ngspice-data = %{version}-%{release}
Requires: ngspice-lib = %{version}-%{release}
Requires: ngspice-license = %{version}-%{release}
Requires: ngspice-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : fftw-dev
BuildRequires : flex
BuildRequires : libXft-dev
BuildRequires : pkgconfig(xaw7)
BuildRequires : readline-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
==================
Ngspice is a mixed-level/mixed-signal circuit simulator. Its code
is based on three open source software packages: Spice3f5, Cider1b1
and Xspice.

%package bin
Summary: bin components for the ngspice package.
Group: Binaries
Requires: ngspice-data = %{version}-%{release}
Requires: ngspice-license = %{version}-%{release}

%description bin
bin components for the ngspice package.


%package data
Summary: data components for the ngspice package.
Group: Data

%description data
data components for the ngspice package.


%package dev
Summary: dev components for the ngspice package.
Group: Development
Requires: ngspice-lib = %{version}-%{release}
Requires: ngspice-bin = %{version}-%{release}
Requires: ngspice-data = %{version}-%{release}
Provides: ngspice-devel = %{version}-%{release}
Requires: ngspice = %{version}-%{release}

%description dev
dev components for the ngspice package.


%package lib
Summary: lib components for the ngspice package.
Group: Libraries
Requires: ngspice-data = %{version}-%{release}
Requires: ngspice-license = %{version}-%{release}

%description lib
lib components for the ngspice package.


%package license
Summary: license components for the ngspice package.
Group: Default

%description license
license components for the ngspice package.


%package man
Summary: man components for the ngspice package.
Group: Default

%description man
man components for the ngspice package.


%prep
%setup -q -n ngspice-42
cd %{_builddir}/ngspice-42
pushd ..
cp -a ngspice-42 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1706133032
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static --with-x --enable-xspice --enable-cider --with-readline=yes --enable-openmp
## make_prepend content
make  %{?_smp_mflags}
%configure --disable-static --with-ngshared --enable-xspice --enable-cider --enable-openmp
## make_prepend end
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --with-x --enable-xspice --enable-cider --with-readline=yes --enable-openmp
## make_prepend content
make  %{?_smp_mflags}
%configure --disable-static --with-ngshared --enable-xspice --enable-cider --enable-openmp
## make_prepend end
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1706133032
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ngspice
cp %{_builddir}/ngspice-%{version}/COPYING %{buildroot}/usr/share/package-licenses/ngspice/a1491cd75848105be6eef7dd4dee78b9bec62718 || :
cp %{_builddir}/ngspice-%{version}/src/spicelib/devices/adms/admst/COPYING %{buildroot}/usr/share/package-licenses/ngspice/c14c8abb8bb45bce3fd27255b2a59b2ba691b2a4 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
## install_append content
/usr/bin/mkdir -p %{buildroot}/usr/bin
/usr/bin/install -c -m 755 src/ngspice %{buildroot}/usr/bin
/usr/bin/mkdir -p %{buildroot}/usr/share/man/man1
/usr/bin/install -c -m 644 man/man1/ngspice.1 %{buildroot}/usr/share/man/man1
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib64/ngspice/analog.cm
/V3/usr/lib64/ngspice/digital.cm
/V3/usr/lib64/ngspice/spice2poly.cm
/V3/usr/lib64/ngspice/table.cm
/V3/usr/lib64/ngspice/xtradev.cm
/V3/usr/lib64/ngspice/xtraevt.cm
/usr/lib64/ngspice/analog.cm
/usr/lib64/ngspice/digital.cm
/usr/lib64/ngspice/spice2poly.cm
/usr/lib64/ngspice/table.cm
/usr/lib64/ngspice/xtradev.cm
/usr/lib64/ngspice/xtraevt.cm

%files bin
%defattr(-,root,root,-)
/usr/bin/ngspice

%files data
%defattr(-,root,root,-)
/usr/share/ngspice/scripts/ciderinit
/usr/share/ngspice/scripts/devaxis
/usr/share/ngspice/scripts/devload
/usr/share/ngspice/scripts/setplot
/usr/share/ngspice/scripts/spectrum
/usr/share/ngspice/scripts/spinit
/usr/share/ngspice/scripts/src/ngspice/cmtypes.h
/usr/share/ngspice/scripts/src/ngspice/cosim.h
/usr/share/ngspice/scripts/src/ngspice/miftypes.h
/usr/share/ngspice/scripts/src/verilator_main.cpp
/usr/share/ngspice/scripts/src/verilator_shim.cpp
/usr/share/ngspice/scripts/vlnggen

%files dev
%defattr(-,root,root,-)
/usr/include/ngspice/sharedspice.h
/usr/lib64/libngspice.so
/usr/lib64/pkgconfig/ngspice.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libngspice.so.0.0.9
/usr/lib64/libngspice.so.0
/usr/lib64/libngspice.so.0.0.9

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ngspice/a1491cd75848105be6eef7dd4dee78b9bec62718
/usr/share/package-licenses/ngspice/c14c8abb8bb45bce3fd27255b2a59b2ba691b2a4

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ngspice.1
