#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ngspice
Version  : 38
Release  : 1
URL      : https://gigenet.dl.sourceforge.net/project/ngspice/ng-spice-rework/38/ngspice-38.tar.gz
Source0  : https://gigenet.dl.sourceforge.net/project/ngspice/ng-spice-rework/38/ngspice-38.tar.gz
Summary  : General-purpose circuit simulator
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0
Requires: ngspice-bin = %{version}-%{release}
Requires: ngspice-data = %{version}-%{release}
Requires: ngspice-license = %{version}-%{release}
Requires: ngspice-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-qmake
BuildRequires : fftw-dev
BuildRequires : flex
BuildRequires : libXft-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xaw7)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
==================
Ngspice is a mixed-level/mixed-signal circuit simulator. Its code
is based on three open source software packages: Spice3f5, Cider1b1
and Xspice.

%package bin
Summary: bin components for the ngspice package.
Group: Binaries
Requires: ngspice-data = %{version}-%{release}
Requires: ngspice-license = %{version}-%{release}

%description bin
bin components for the ngspice package.


%package data
Summary: data components for the ngspice package.
Group: Data

%description data
data components for the ngspice package.


%package license
Summary: license components for the ngspice package.
Group: Default

%description license
license components for the ngspice package.


%package man
Summary: man components for the ngspice package.
Group: Default

%description man
man components for the ngspice package.


%prep
%setup -q -n ngspice-38
cd %{_builddir}/ngspice-38

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1674504618
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1674504618
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ngspice
cp %{_builddir}/ngspice-%{version}/COPYING %{buildroot}/usr/share/package-licenses/ngspice/1d84d6ffeb0dfa5292191dd296df378d75ae3cb3 || :
cp %{_builddir}/ngspice-%{version}/src/spicelib/devices/adms/admst/COPYING %{buildroot}/usr/share/package-licenses/ngspice/c14c8abb8bb45bce3fd27255b2a59b2ba691b2a4 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ngspice

%files data
%defattr(-,root,root,-)
/usr/share/ngspice/scripts/setplot
/usr/share/ngspice/scripts/spectrum
/usr/share/ngspice/scripts/spinit

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ngspice/1d84d6ffeb0dfa5292191dd296df378d75ae3cb3
/usr/share/package-licenses/ngspice/c14c8abb8bb45bce3fd27255b2a59b2ba691b2a4

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ngspice.1
